### ISSUE TITLE
add boilerplate's for services and controllers

### ISSUE THREAD

**Issue by cupsadarius** [generaptr/generaptr#32]
add boilerplate's for express server, config, controllers and services

**Comment by StefanBalea** [comment]
**General information:**

All generated API configurations will be placed in /api/configs. At this moment we have only one configuration generated: "index.js" for sequalize module. "index.js" should have _profile configuration_ so the API can be deployed on different environments. Format for "index.js":

```
{
	"development": {
		"uri": "mysql://root:root@127.0.0.1:3306/app_generaptr",
		"username": "root",
		"password": "root",
		"database": "app_generaptr",
		"host": "127.0.0.1",
		"dialect": "mysql",
		"port": "3306"
	},
	"production": {
		"uri": "mysql://root:root@127.0.0.1:3306/app_generaptr",
		"username": "root",
		"password": "root",
		"database": "app_generaptr",
		"host": "127.0.0.1",
		"dialect": "mysql",
		"port": "3306"
	}
}
```

**Configurations**
New files added:

- _express.js_ : contains the following configurations: bodyParser, express and cors registration.
e.g.

```
...
const cors = require('../middlewared/cors.js');

module.exports = (app) => {
   app.use(bodyParser.json());
   app.use(bodyParser.urlencoded({extended: false}));
   app.use(morgan(generalAppConfig.profile)); // need to be generated
   app.use(cors);

   return app;
}
```

- _router.js_ : contains API controllers registration.
All controllers will be read from "controllers" folder.
e.g.
```
const router = require('express').Router();

/**
* Import needed controllers
*/
const modelController = require(`../controllers/${model}Controller`);

/**
 * Agregates all the controllers.
 */
router.use(`/{model}s`, modelController);

module.exports.router = router;
```

All these configurations will be called inside "server.js" file.

**Services**
Service files will be placed inside _/api/services_ folder. 
_File naming_: `${model}Service.js`;
_Methods_: `save${model}`, `get${model}`, `get${modelS}`, `delete${model}`, `update${model}`.

**Controllers**
Controller files will be placed inside _/api/controllers_ folder.
_File naming_: `${model}Controller.js`

**Comment by cupsadarius** [comment]
For the database configuration I agree multiple environments are required but I don't wanna put the user through another database info question track so maybe we'll add the development info and mock the production or we could expect that prod config would be passed through env variables.

**Comment by StefanBalea** [comment]
I agree. Just one mock for "production/test" environment. In this case, if the user wants to deploy the API on a test server, he can create proper configuration for that environment and set an ENV variable like "profile". All configurations will be loaded automatically by ENV variable. If no default ENV variable is found, we can use "development" profile by default.

**Comment by cupsadarius** [comment]
I agree ..
