### ISSUE TITLE
generate models for relational databases

### ISSUE THREAD

**Issue by cupsadarius** [generaptr/generaptr#33]
Generate sequelize models and repositories based on the schema

As seen on [Sequelize Docs](http://docs.sequelizejs.com/), Sequelize supports PostgreSQL, MySQL, SQLite and MSSQL which would already cover a good part of the relational databases.

**Comment by cupsadarius** [comment]
**Config**
In relation to the discussion we had on #32, in the scope of this I'll rename the `src/configs/index.js` in `src/configs/database.js`, it will hold environment based configs for connecting to the database.

**Model**
Model files will be placed inside `/api/src/models` folder.
File naming: `${model}.js;`
As the model is odm specific I won't describe here the interfaces which would be exposed, and due to this reason we will implement a _repository_ layer which would always export the same interface.

**Repository**
Repository files will be placed inside `/api/src/repositories` folder.
File naming: `${model}Repository.js;`
Methods: save, get, getAll, delete, update, count.
A factory which returns instances of repositories would be the default export of the repositories bundle.

```
export class RepositoryFactory {
  public getRepository(model: string): IRepositroy;
}

export default new RepositoryFactory();
```

**Comment by StefanBalea** [comment]
I agree. :+1:
