### ISSUE TITLE
refactor file names

### ISSUE THREAD

**Issue by cupsadarius** [generaptr/generaptr#47]
We should refactor some file names, for example we don't need all files inside commons/utils to have the Util appended to their name, it can clearly be seen from the import that it's a util class.
The same goes for fileOperations, handlers and preprocessors.

**Comment by cupsadarius** [comment]
@StefanBalea What do you think?

**Comment by StefanBalea** [comment]
I agree.

**Comment by cupsadarius** [comment]
fixed as part of 1b22da5bba688acb24090c13aa57b109562cadb2
